name: Trigger auto deployment for jollybeach-2c1b6a13

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/jollybeach-2c1b6a13-AutoDeployTrigger-93aa4b44-76ef-4358-9dea-1327a1167def.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JOLLYBEACH2C1B6A13_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JOLLYBEACH2C1B6A13_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JOLLYBEACH2C1B6A13_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.JOLLYBEACH2C1B6A13_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JOLLYBEACH2C1B6A13_REGISTRY_PASSWORD }}
          containerAppName: jollybeach-2c1b6a13
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


